# Generated by Django 5.2 on 2025-09-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_options_movie_kinopoisk_url_movie_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='kinopoisk_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
    ]
