# Generated by Django 5.2 on 2025-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movie_kinopoisk_url_remove_movie_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
