# Generated by Django 5.2 on 2025-09-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-time_create'], 'verbose_name': 'Фильм/Сериал', 'verbose_name_plural': 'Фильмы/Сериалы'},
        ),
    ]
