# Generated by Django 5.2 on 2025-10-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['time_create'], 'verbose_name': 'Фильм/Сериал', 'verbose_name_plural': 'Фильмы/Сериалы'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_published',
        ),
    ]
