# Generated by Django 5.2 on 2025-10-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_options_remove_movie_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cat',
        ),
        migrations.DeleteModel(
            name='TagPost',
        ),
    ]
